# Generated by Django 4.0.5 on 2022-07-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
