# Generated by Django 4.0.5 on 2022-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_chief_author_slug_publish_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': True, 'verbose_name': 'مقاله ', 'verbose_name_plural': 'مقالات '},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'managed': True, 'verbose_name': 'نویسنده ', 'verbose_name_plural': 'نویسندگان '},
        ),
        migrations.AlterModelOptions(
            name='chief',
            options={'managed': True, 'verbose_name': 'سر دبیر', 'verbose_name_plural': 'سر دبیران'},
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={'managed': True, 'verbose_name': 'نشر ', 'verbose_name_plural': 'ناشر '},
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=30, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='author',
            name='family',
            field=models.CharField(max_length=50, verbose_name=' نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='chief',
            name='family',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی '),
        ),
        migrations.AlterField(
            model_name='chief',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام '),
        ),
        migrations.AlterField(
            model_name='publish',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام نشر'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='article_db',
        ),
        migrations.AlterModelTable(
            name='author',
            table='author_db',
        ),
        migrations.AlterModelTable(
            name='chief',
            table='chief_db',
        ),
        migrations.AlterModelTable(
            name='publish',
            table='publish_db',
        ),
    ]
